from __future__ import annotations

from typing import Any


FUNCTION_REGISTRY: list[dict[str, Any]] = [
    {
        "id": "inspect_source",
        "name": "Inspect Source",
        "section": "main",
        "description": "Parse the uploaded notebook-converted Python file and inventory all extracted definitions and blocks.",
        "handler": "inspect_source",
        "params": [],
        "returns": ["text", "table"],
    },
    {
        "id": "prepare_dataset_metadata",
        "name": "Prepare Dataset Metadata",
        "section": "main",
        "description": "Load the NIH metadata CSV, one-hot encode the 14 labels, clean ages, and optionally create train/val/test splits from list files.",
        "handler": "prepare_dataset_metadata",
        "params": [
            {"name": "csv_file", "type": "file", "required": True, "accept": ".csv"},
            {"name": "train_list_file", "type": "file", "required": False, "accept": ".txt"},
            {"name": "test_list_file", "type": "file", "required": False, "accept": ".txt"},
        ],
        "returns": ["text", "table"],
    },
    {
        "id": "validate_dataset_match",
        "name": "Validate Dataset Match",
        "section": "main",
        "description": "Compare CSV image ids with files in the image folder and report overlap, missing ids, and extras before training.",
        "handler": "validate_dataset_match",
        "params": [
            {"name": "csv_file", "type": "file", "required": True, "accept": ".csv"},
            {"name": "image_dir", "type": "directory", "required": True},
            {"name": "sample_limit", "type": "number", "required": False, "default": 20},
        ],
        "returns": ["table", "text"],
    },
    {
        "id": "sample_image_preview",
        "name": "Sample Image Preview",
        "section": "main",
        "description": "Recreate the notebook sample-visualization block for a subset of training images.",
        "handler": "sample_image_preview",
        "params": [
            {"name": "image_dir", "type": "directory", "required": True},
            {"name": "sample_count", "type": "number", "required": False, "default": 10},
        ],
        "returns": ["image", "table"],
    },
    {
        "id": "build_model_summary",
        "name": "Build DenseNet121",
        "section": "main",
        "description": "Instantiate the DenseNet121 classifier with the notebook's custom classification head.",
        "handler": "build_model_summary",
        "params": [
            {"name": "num_classes", "type": "number", "required": False, "default": 14},
            {"name": "device", "type": "dropdown", "required": False, "default": "auto", "options": ["auto", "cpu", "gpu"]},
        ],
        "returns": ["text"],
    },
    {
        "id": "train_model_workflow",
        "name": "Train Model",
        "section": "main",
        "description": "Run the original DenseNet121 training loop with validation AUC tracking and training-curve artifacts.",
        "handler": "train_model_workflow",
        "async": True,
        "params": [
            {"name": "image_dir", "type": "directory", "required": True},
            {"name": "epochs", "type": "number", "required": False, "default": 5},
            {"name": "lr", "type": "number", "required": False, "default": 0.0001},
            {"name": "batch_size", "type": "number", "required": False, "default": 32},
            {"name": "device", "type": "dropdown", "required": False, "default": "auto", "options": ["auto", "cpu", "gpu"]},
        ],
        "returns": ["chart", "json"],
    },
    {
        "id": "run_inference_analysis",
        "name": "Inference And Misclassifications",
        "section": "main",
        "description": "Run model inference on the test split, calculate misclassifications, and export structured error records.",
        "handler": "run_inference_analysis",
        "params": [
            {"name": "image_dir", "type": "directory", "required": True},
            {"name": "threshold", "type": "number", "required": False, "default": 0.5},
            {"name": "device", "type": "dropdown", "required": False, "default": "auto", "options": ["auto", "cpu", "gpu"]},
        ],
        "returns": ["table", "csv"],
    },
    {
        "id": "generate_structured_error_data",
        "name": "Structured Error Data",
        "section": "main",
        "description": "Generate prompt-ready structured error records and age-group metadata for the misclassified set.",
        "handler": "generate_structured_error_data",
        "params": [],
        "returns": ["table", "text"],
    },
    {
        "id": "run_llm_reasoning",
        "name": "LLM Error Reasoning",
        "section": "main",
        "description": "Analyze structured misclassifications with either the notebook's local LLM path or the rule-based fallback.",
        "handler": "run_llm_reasoning",
        "params": [
            {"name": "sample_size", "type": "number", "required": False, "default": 200},
            {"name": "strategy", "type": "dropdown", "required": False, "default": "rule_based", "options": ["rule_based", "local_llm"]},
        ],
        "returns": ["table", "csv"],
    },
    {
        "id": "build_error_taxonomy",
        "name": "Error Taxonomy",
        "section": "main",
        "description": "Aggregate LLM reasoning into the structured error taxonomy, severity summaries, and disease breakdowns.",
        "handler": "build_error_taxonomy",
        "params": [],
        "returns": ["table", "chart", "csv"],
    },
    {
        "id": "analyze_bias",
        "name": "Bias Detection",
        "section": "main",
        "description": "Replicate gender and age-group bias analysis, including chi-square statistics when SciPy is available.",
        "handler": "analyze_bias",
        "params": [],
        "returns": ["table", "chart"],
    },
    {
        "id": "label_inconsistency_detection",
        "name": "Label Inconsistency",
        "section": "main",
        "description": "Generate simulated radiology reports and detect label-report inconsistencies with the notebook heuristics.",
        "handler": "label_inconsistency_detection",
        "params": [{"name": "sample_size", "type": "number", "required": False, "default": 200}],
        "returns": ["table", "chart"],
    },
    {
        "id": "dataset_error_pattern_analysis",
        "name": "Dataset Error Patterns",
        "section": "main",
        "description": "Create confusion summaries, top confused disease pairs, and global dataset-level error trend metrics.",
        "handler": "dataset_error_pattern_analysis",
        "params": [],
        "returns": ["chart", "table", "json"],
    },
    {
        "id": "gradcam_visualization",
        "name": "Grad-CAM Visualizations",
        "section": "main",
        "description": "Render Grad-CAM overlays for representative misclassified samples and compare true vs predicted attention.",
        "handler": "gradcam_visualization",
        "params": [{"name": "image_dir", "type": "directory", "required": True}],
        "returns": ["image"],
    },
    {
        "id": "clean_age",
        "name": "Clean Age",
        "section": "advanced",
        "description": "Utility function extracted directly from the notebook for removing non-numeric characters from age fields.",
        "handler": "clean_age",
        "params": [{"name": "val", "type": "text", "required": True}],
        "returns": ["text"],
    },
    {
        "id": "clean_age_capped",
        "name": "Clean Age Capped",
        "section": "advanced",
        "description": "Companion utility from the notebook that caps invalid ages outside 0-110.",
        "handler": "clean_age_capped",
        "params": [{"name": "age", "type": "number", "required": True}],
        "returns": ["text"],
    },
    {
        "id": "get_age_group",
        "name": "Get Age Group",
        "section": "advanced",
        "description": "Map a numeric age to the notebook's demographic bucket labels.",
        "handler": "get_age_group",
        "params": [{"name": "age", "type": "number", "required": True}],
        "returns": ["text"],
    },
    {
        "id": "format_error_prompt",
        "name": "Format Error Prompt",
        "section": "advanced",
        "description": "Build the structured auditing prompt used for LLM-based error reasoning.",
        "handler": "format_error_prompt",
        "params": [{"name": "record", "type": "json", "required": True}],
        "returns": ["text"],
    },
    {
        "id": "rule_based_llm_analysis",
        "name": "Rule-Based LLM Fallback",
        "section": "advanced",
        "description": "Use the notebook's fallback logic to categorize an error record without loading a local LLM.",
        "handler": "rule_based_llm_analysis",
        "params": [{"name": "record", "type": "json", "required": True}],
        "returns": ["json"],
    },
    {
        "id": "query_llm",
        "name": "Query Local LLM",
        "section": "advanced",
        "description": "Send a prompt to the configured local Hugging Face causal LM and parse a JSON response.",
        "handler": "query_llm",
        "params": [
            {"name": "prompt", "type": "textarea", "required": True},
            {"name": "retries", "type": "number", "required": False, "default": 2},
        ],
        "returns": ["json"],
    },
    {
        "id": "generate_simulated_report",
        "name": "Generate Simulated Report",
        "section": "advanced",
        "description": "Expose the notebook's simulated radiology report generator used for label inconsistency testing.",
        "handler": "generate_simulated_report",
        "params": [
            {"name": "true_labels", "type": "text", "required": True},
            {"name": "pred_labels", "type": "text", "required": False},
        ],
        "returns": ["text"],
    },
    {
        "id": "detect_inconsistency",
        "name": "Detect Inconsistency",
        "section": "advanced",
        "description": "Run the notebook's report-vs-label inconsistency detector on arbitrary inputs.",
        "handler": "detect_inconsistency",
        "params": [
            {"name": "true_labels_str", "type": "text", "required": True},
            {"name": "report_text", "type": "textarea", "required": True},
        ],
        "returns": ["json"],
    },
    {
        "id": "health",
        "name": "Environment Health",
        "section": "advanced",
        "description": "Inspect backend runtime health, loaded state keys, and source file wiring.",
        "handler": "health",
        "params": [],
        "returns": ["json"],
    },
]

